### ISSUE TITLE
Setting name for inputs

### ISSUE THREAD

**Issue by thomas15v** [rajasegar/JADE-Bootstrap#2]
```jade
+modal("Modal title","addDaemon")
        form(action='/admin/add_daemon', method="post")
            input(type='hidden', name="id", id="editid")
            +input('text','name', 'A nice name for the daemon', "Name")
            +input('text','ip', 'The http address from the daemon.', "Address")
            +input('text','key', 'The Key for the daemon', "Key")
            +input('text','group', 'The group for the daemon', "Group")
            +submit-primary('Add')
```

I have this code. Only my posts don't send data because the name tag is missing. And I can't figure out a way to bruteforce that in their :worried:.

**Comment by rajasegar** [comment]
Fixed in the latest commit , now you can add name as a parameter to the mixin just like you mentioned, so now the syntax will be
+input(type,id,placeholder,label, name)

**Comment by hagabaka** [comment]
The checkbox and radio mixins still don't allow specifying names.

**Comment by rajasegar** [comment]
@hagabaka 
Fixed in the latest commit
https://github.com/rajasegar/JADE-Bootstrap/commit/8480a5c2601092a0968abd7374423cc0f3e78a49
Now you can use
```
+checkbox(text,name,id)
+checkbox-inline(text,name,id)
+radio(text,name,id)
+radio-inline(text,name,id)
```
